[[https://www.youtube.com/watch?v=K-FtLWc8TxI][📈️ Архитектура как функция от? Или как недостаток здравого смысла убивает архитектуру. / Кривошеев Евгений]]

** Points of view: Представление архитектуры в виде квадратиков и стрелочек лишь одна из точек зрения.

- Тут важен контекст: он задаёт ограничения для дизайна. Нужно будет принять много решений (и ещё больше отложить, если возможно).
- 1. Сформулируй архитектуру в виде требований к компонентам. Затем формулируются требования к подкомпонент и т.д. (рекурсивно вниз).
- 2. Сформулируй архитектуру в виде перечня рисков.


** Формально архитектура - это функция от внешних (со стороны заказчика) функциональных требований и внешних же требований качества.

- Формально определять архитектуру очень рискованно, в конце проекта мы можем узнать что не пропустили важное требование и нужно переделывать или закрывать проект.
- Внешнее требование качества это производительность и т.п.


** Но этого мало, поэтому нужны ещё:

- 1. Внутренние (со стороны команды) функциональные требования. Например, заказчик не просил логирование и мониторинг, но команда понимает, что они нужны.
- 2. Внутренние требования качества: поддерживаемость и тестируемость.
- 3. Внутреннее руководство по дизайну (руководство по проектированию и руководство по стилю кодирования): используем DI или нет, используем singleton или нет и т.п. достаточно сформулировать настолько просто и про разные уровни системы. Понимай является ли данное руководство результатом нашего опыта и боли (регламент написанный кровью - очень рискованно не учитывать) или это что-то внешнее, не обязательно имеющее отношение к проекту.
- 4. Personal pain experience важен, но нужно смотреть шире и проверять другие гипотезы, когда можно облажаться (например, взять библиотеку и понять, что она работает очень медленно).
- 5. Доверие команде: отдавай сеньорам принимать больше решений, а джуниорам сильно меньше. Если доверять все, то это vendor lock in. Если не доверять совсем, то команда растет очень медленно.
- 6. Архитектура продукта определяется организацией компании. Если компания большая и команды мало общаются друг с другом, то не будет концептуальной целостности без человека, который будет отвечать за это (логи пишем так-то, мониторинг такой-то и так далее).
- 7. Ресурсы: деньги, люди и время. А также то, что часто не учитывается: подрядчики, доверие от команды менеджменту (будут программисты партизанить или нет).
- 8. Внутрикорпоративные ограничения (нам хватит Постгреса, но фирма уже купила Оракл и принуждает использовать его). Или менеджер отдела разработки в конфликте с менеджером отдела тестирования, соответственно, приложение получится нетестируемым. Здесь предполагаем, что межличностный конфликт устранить дороже, чем найти другое решение.
- 9. С кем мы интегрируемся - мы пишем на Хаскеле, а нам нужно интегрироваться с легаси системами: библиотеки, форматы данных и т.п. может в maven или npm есть готовые либы?
- 10. Законодательные ограничения: защита персональных данных увеличивает стоимость и поддержку.
- 11. Vendor lock in - сначала быстро и дешево на старте, а потом все медленнее и дороже, когда нам нужны нестандартные вещи.


** Примеры:
- 1. Команду можно растить только давая все более сложные задачи. Тут будут проблемы и это нужно понимать всей команде, включая менеджеров. Чем больше команда будет лажать, тем больше она будет учиться. Если не давать ошибаться, то рост будет очень медленным. Тут менеджеры должны принять решение будут ли они иметь дело с этим риском или нет.
- 2. У нас две географически распределенные команды. Поэтому мы разбиваем систему на два сервиса, чтобы четко определить взаимодействие между сервисами, а дальше каждая команда сможет эффективно делать свой сервис.


** Проблема: решений нужно принять много, как учесть все?
- 1. Определи приоритеты и прими только ключевые решения, а остальные делегируй.
- 2. Если можно не принимать решение и в этом нет высокого риска, то отложи его.
