[[https://www.youtube.com/watch?v=Y12_T50LRhY][🏢 Архитектура (Use Case Driven Development)/ Рыжиков Николай]]

** Что такое архитектура?
- Архитектура - это принятые ключевые решения. Если потом их поменять, то это будет дорого.
- Архитектура - это разбиение системы на компоненты, определение правил взаимодействия компонентов. Архитектура определяет ограничения. Состоит из элементов, коннекторов и данных. Элемент системы сам может состоять из других элементов.
- Корпускулярные системы (состоят из однородных элементов, например, как люди в обществе : каждый может общаться с каждым, нет ограничений на взаимодействие) и жесткие системы (состоят из сильно специализированных элементов, а на взаимодействие элементов наложены ограничения, например, органы в организме). Эти системы чередуются. Это применимо и к IT.

** Виды архитектур
  - Хаос (нет ограничений);
  - Pipeline (каждый элемент делает что-то одно плюс стандартный интерфейс);
  - Layered (нижние слои не знают про верхние).

** Многие проблемы изначально содержат противоречия и нужно выбрать что-то одно, отказавшись от остального.
  - Например, CAP - выбери любые два свойства. Тут важно подумать, а не отказался ли я от необходимого для моей системы свойства? Если да, то нужно начать заново и, вероятно, ещё раз обсудить с заказчиком, чтобы он принял бизнес-решение и разрешил противоречие на уровне архитектуры.

** Достаточно ли быть хорошим разработчиком, чтобы принять хорошее архитектурное решение?
  - Нет.
  - Чтобы выбрать подходящий компромисс в архитектуре нужно хорошо понимать предметную область. Сложность находится в предметной области, а не в технологиях.

** Что делать?
- Разберись в ограничениях: бизнес (что ему действительно нужно, а не то, что про это говорят) и команду (насколько она развита технически, насколько хорошо понимает потребности бизнеса). Заказчик должен проверить, что данная архитектура соответствует потребностям его бизнеса как сейчас, так и через 5-10 лет. Если команда из начинающих, то они не реализуют технологически сложную архитектуру, это нужно учитывать.
- Всем специалистам общаться в одних и тех же терминах, чтобы уменьшить ошибки коммуникации.
- Разбей систему на более простые компоненты.
- Если предметная область простая, то делай простые модели. MVC.
- Если предметная область сложная, то MVC + use case. Двигаться от частного к общему. В какой-то момент случится deep insight (при этом нельзя пропустить этап частных случаев).
- Use Case driven development: описывать и реализовывать простые use case вместо сложной настраиваемой модели (меньше связанность системы).
- В какой-то момент множество реализаций use cases заменяется одной моделью. Потом опять пишутся частные реализации use cases и т.д.
