[[https://www.youtube.com/watch?v=_1owUnNojr4][👨 Хекслет: интервью Кирилла Мокевнина с Пименовым Алексеем]]

** Потребности бизнеса
  - Большинство технических решений диктуется потребностями бизнеса, а не предпочтениями разработчиков.
  - Например, бизнесу нужно быстро реагировать на изменения и именно поэтому разработка как обеспечивающая система должна быть гибкой и быстро вносить изменения в код.
  - Дисфункция: менеджеры считают стоимость и оценивают риски без привлечения разработчиков.

** Оценки первого порядка
  - При оценке стоимости разработки и рисков обычно менеджеры оценивают стоимость и риски только первого порядка и НЕ оценивают стоимость и риски второго и далее порядков.
  - Например, оценивается количество часов разработки, а то, что этот код, возможно, будет очень тяжело поддерживать (и бизнес будет платить за это впоследствии), это не учитывается.
  - Пример: оплатить Хекслет можно только карточкой через Stripe и в Хекслете решили не добавлять другие платежные системы (хотя конкретно это можно сделать быстро). Это было бизнес-решение, чтобы сделать систему проще и как следствие дешевле в целом (иначе во всех новых фичах пришлось бы учитывать, что есть несколько способов оплаты, это и есть стоимость второго порядка).

**  А есть ли тут Agile?
  - Если на уровне менеджмента хотят экспериментировать, но разработчик не может быстро проверить изменения в коде на своей машине или если другой разработчик может повлиять на  его работу (например, через общую базу данных), то никакого Agile тут нет.
  - Поэтому пока на инженерном уровне все очень хрупко и неповоротливо, то и на уровне бизнеса не получится быстро делать изменения.

** Если менеджеры просят оценить в деньгах техническое изменение, то оцени это как стоимость простоя или как стоимость риска

** 3 типа организаций (или отделов внутри организации):
  - enterprise – характеризуется стабильностью и отвечает за зарабатывание денег сейчас, люди максимально ориентированы на поддержание статуса-кво;
  - startup – характерен постоянными изменениями для поиска способов увеличения прибыли, люди максимально ориентированы на продукт;
  - R&D – относительно стабилен, люди максимально опытные технологически и нацелены на создание новых технологических решений.

** Безтелефонные часы
  - Договоренность в фирме, при которой разработчик не отвечает на звонки и сообщения в определенные часы, чтобы сконцентрированно работать над кодом.

** Дисфункция: разработчики считают, что менеджеры не могут сформулировать проблему, а менеджеры считают, что разработчики не могут решить эту проблему

** Чем больше людей работает в компании, тем дороже управленческие ошибки и чтобы их компенсировать компания должна хорошо зарабатывать

** Почему инженеры хотят делать задачи и не хотят общаться с менеджерами?
  - Потому что инженеры перегружены. Сними с них часть задач и они будут общаться.
  - 100% утилизация МКАДа - это пробка и толку от этого мало.

** Высокая вариативность нетиповых задач в IT

** Kanban в IT:
  - Канбан - это метод проведения организационных изменений.
  - Вытягивание задач по сигналу (важно!).
  - Колонки на канбан-доске:
    - todo (общий список всех задач),
    - plan (сюда задачи попадают по сигналу - продуктовый менеджер может легко решить, что сейчас самое важное, а приоритезировать все задачи очень затратно),
    - in work,
    - done.
  - Лимит на незавершенную работу в нескольких столбцах: in work и ready for testing. Так менеджер видит, что проблема в тестировании. Разработчик в это время задачи НЕ делает.

** Scrum в IT:
  - Для инновационных продуктов.
  - Для команд из высокомотивированных профессионалов.
  - Дорогой - собрания стоят дороже (люди в это время не делают задачи).

** Книги:
  - Голдрат Цель;
  - Голдрат Цель 2 (Дело не в везении);
  - Рэй Иммельман Босс бесподобный или бесполезный.
