[[https://www.youtube.com/watch?v=EEq1wdM2M2w][👤 Ментальное программирование / Мокевнин Кирилл]]

** Чем ближе код к терминам бизнеса и продукта, тем лучше. Код должен быть написан в той же ментальной модели, что и описан бизнес.
  - Плохо: 
    #+BEGIN_SRC ruby
      session[:user_id] = user.id
    #+END_SRC
  - Хорошо: 
    #+BEGIN_SRC ruby
      sign_in(user)
    #+END_SRC

** Повышай уровень абстракции (то же, что и предыдущее по сути)
  - Плохо:
    #+BEGIN_SRC ruby
      if user.company? && user.company_active? && user.money > 50
    #+END_SRC
  - Хорошо:
    #+BEGIN_SRC ruby
      if user.can_edit_company? #(Это уже ближе к бизнесу, а детали скрыты)
    #+END_SRC
  - Правило: если if идёт по одному агрегату (user), то выделяй его в метод. И неважно, что этот метод будет использоваться один раз. Важно то, что такой код будет соответствовать ментальной модели (бизнеса).

** Если вместо хорошего имени функции или модуля ты пишешь комментарий, то возможно ты недостаточно думал над формированием абстракции.
Название сильно короче комментария и требует намного больше усилий. Проблема в том, что так весь код будет из комментариев без понятной модели в голове.

** Бизнес фича более важна, чем ветка (это уже деталь реализации)
  #+BEGIN_SRC sh
    git checkout -b signup-new vs git flow feature start signup-new
  #+END_SRC

** Семантический разрыв - из кода сложно понять, что же нужно было сделать для бизнеса.

** Антипаттерны
- Нарушение контракта
  - Было:
    #+BEGIN_SRC ruby
      u = User.first
      u.destroy # удаляет из базы
    #+END_SRC
  - Стало:
    #+BEGIN_SRC ruby
      u = User.first
      u.destroy # помечает в базе как удаленный
    #+END_SRC
  - Проблема: мы нарушили контракт, так как используем ту же функцию, а поведение другое.
  - Решение: добавь новую функцию u.mark_as_deleted

** Принципы ООП
  - GRASP
    - Информационный эксперт: если мы постоянно вызываем метод и передаём туда объект, то этот метод должен быть в этом объекте.
    - Высокое сцепление: помести код выполняющий одну задачу в одно место.
    - Низкая связанность: как можно меньше модулей должно зависеть друг от друга.
  - SOLID
  - CQS
    - Задавая вопрос не изменяй ответ.
    - Если вызываешь метод user.is_admin, то он просто должен вернуть true/false и НЕ изменять внутреннее состояние объекта.
    - is_valid только возвращает булевое значение, а вот validate только меняет состояние объекта (заполняет список ошибок).
    - Это может прокатить, если объект живет ровно столько времени, сколько живет HTTP запрос-ответ, но для долгоживущих объектов это полностью нерабочий вариант.
  - Law of Demeter
  - Single level of abstraction principle
    - Если на данном уровне абстракции работаешь с объектами, то НЕ иди на этом же уровне абстракции в базу данных.

** Практики
  - Первый раз - лучший
    - Если пишется авторизация через Фейсбук и мы понимаем, что потом мы добавим авторизацию через Вконтакт, то нужно с первого раза писать хорошо. Чтобы можно было показать как эталон, когда начнут писать следующую фичу.
  - Не оставляй разбитые окна
    - Если код хорошо написан, то будет сложно нарушать принципы в отдельно взятых местах.
  - Чёрные и белые списки
    - Зависит от контекста: сколько у нас возможных состояний и как именно нужно ограничивать доступ.
  - Безопасность по умолчанию
    - Вагон по умолчанию блокирует колёса.
    - Лифт блокируется при обрыве троса чисто механическими средствами (это не зависит ни от человека, ни от электричества).
    - Garbage collector как пример безопасного управления памятью по умолчанию.
  - API
    - Смысл TDD не в написании тестов до кода, а в том, что код нужно писать только после того как мы поняли как мы будем его использовать, т.е. когда определили API.
  - Получай и используй отдельно
    - Плохо:
      #+BEGIN_SRC ruby
        sign_in(create(:user))
      #+END_SRC
    - Хорошо:
      #+BEGIN_SRC ruby
        user = create(:user)
        sign_in(user)
        # Это удобно для отладки, чтобы посмотреть значение переменной user.
      #+END_SRC

** Слишком рано не бывает
    - Мы не будем использовать библиотеку ради пары методов. В итоге мы строим свой велосипед, повторяя существующий инструмент.
    - Бери сразу готовую библиотеку.

** Выделяем абстракции сразу, а не при дублировании
    - Этот момент не настанет. Почти никто не будет ждать трёх повторений, чтобы что-то зарефакторить. Скорее всего уже кто-то другой будет работать с этим кодом.
    - А если ещё и тестов нет, то менять вообще страшно.

** Extreme programming
    - Писать код так будто его писал один квалифицированный программист.
    - Парное программирование.
    - TDD
