[[https://www.youtube.com/watch?v=4uaAxeFTVZ4][🏃Мотивация 3.0 / Пименов Алексей]]

** Мотивация 1.0: удовлетворение потребностей (базовых).
  - Не объясняет действие системы сдержек и противовесов.

** Мотивация 2.0 (подчинение): пряник и кнут (стремится к удовольствию и избегает наказания).
  - Может гасить внутреннюю мотивацию.
  - Может вытеснять желаемое поведение.
  - Может вызывать привыкание.
  - Может поощрять поиск легких путей и неэтичное поведение.

** Мотивация 2.1 (подчинение + немного самореализации): пряник + немного самореализации и кнут.
  - Корректирует часть проблем мотивации 2.0 (старается избегать закрепления нежелательного поведения).
  - Можно ли разнообразить рутинную задачу?
  - Если нет, то дать человеку дополнительные деньги и объяснить, что это рутинная задача, поэтому он получает за нее дополнительные деньги и (важно) может выбрать способ реализации.
  - Если да (или задача не рутинна), то обеспечь условия работы сотруднику и (важно) признай его заслуги и дай коммуницировать с другими людьми. Если здесь предложить дополнительные деньги, то можно убить мотивацию. Человеку нужно дать деньги именно за результат.

** Мотивация 3.0 (участие): работа в состоянии потока является источником мотивации:
  - Работа в состоянии потока: задачи не слишком тяжелые и не слишком легкие.
  - Сложность задач растет соответственно росту квалификации сотрудника. Если быстрее, то сотрудник сильно перегружен; если медленнее, то сотрудник начинает скучать.
  - Гигиенические факторы (обеспечивает работодатель):
    - понятно, что требуется сделать.
    - созданы рабочие условия, необходимые для работы.
    - зарплата не ниже средней по рынку.
  - Мотивационные факторы (обеспечивает работодатель):
    - может выбирать как решать задачи (при этом несет ответственность за результат).
    - достаточно часто находится в состоянии потока. 
  - Личный выбор (сотрудник):
    - заниматься делом, которое нравится.
    - расти профессионально в выбранном деле.
  - Тренировать то, что человек делает хорошо, а что делает плохо компенсировать другими людьми в команде.

** Литература:
  - Ричард Дафт "Менеджмент";
  - Михай Чиксенмихай "Поток. Психология оптимального переживания";
  - Дэниел Пинк "Драйв. Что на самом деле нас мотивирует".
